services:
  mariadb:
    image: mariadb:11.2.2-jammy
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3307"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 1m
      timeout: 5s
      retries: 3

  node:
    image: ghcr.io/alexispet/final-test-noahsmo/api:develop
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: 3000
    volumes:
      - .:/app
    ports:
      - "80:3001"
    command: npm run start
    depends_on:
      mariadb:
        condition: service_healthy