---
- hosts: "webservers"
  remote_user: "admin"
  become: true
  become_method: sudo

  name: Installing Docker
  tasks:
    - name: Install aptitude using apt
      apt:
        update_cache: yes
        name: aptitude
        state: latest
        force_apt_get: yes

    - name: Install required system packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip']
        state: latest
        force_apt_get: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: latest
        force_apt_get: yes

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present

    - name: Add admin to docker group
      user:
        name: admin
        groups: docker
        append: yes

    - name: Start and enable systemd service
      systemd:
        name: docker
        state: started
        enabled: yes

