---
- hosts: webservers
  remote_user: admin
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: present
      vars:
        ansible_become: true

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present
      vars:
        ansible_become: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      vars:
        ansible_become: true

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      vars:
        ansible_become: true

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: present
      vars:
        ansible_become: true

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: present
      vars:
        ansible_become: true

    - name: Add admin to docker group
      user:
        name: admin
        groups: docker
        append: yes
      vars:
        ansible_become: true

    - name: Start and enable systemd service
      systemd:
        name: docker
        state: started
        enabled: yes
      vars:
        ansible_become: true
