#---
#- name: Install Docker and Configure
#  hosts: webservers
#  remote_user: admin
#  become: true
#  become_method: sudo
#  gather_facts: true
#
#  tasks:
#    - name: Install aptitude using apt
#      ansible.builtin.apt:
#        name: aptitude
#        state: present
#
#    - name: Install required system packages
#      ansible.builtin.apt:
#        name:
#          - apt-transport-https
#          - ca-certificates
#          - curl
#          - software-properties-common
#          - python3-pip
#        state: present
#
#    - name: Add Docker GPG apt Key
#      ansible.builtin.apt_key:
#        url: https://download.docker.com/linux/ubuntu/gpg
#        state: present
#
#    - name: Add Docker Repository
#      ansible.builtin.apt_repository:
#        repo: deb https://download.docker.com/linux/ubuntu bionic stable
#        state: present
#
#    - name: Update apt and install docker-ce
#      ansible.builtin.apt:
#        name: docker-ce
#        state: present
#
#    - name: Install docker-compose
#      ansible.builtin.pip:
#        name: docker-compose
#        state: present
#
#    - name: Add admin to docker group
#      ansible.builtin.user:
#        name: admin
#        groups: docker
#        append: yes
#
#    - name: Start and enable systemd service
#      ansible.builtin.systemd:
#        name: docker
#        state: started
#        enabled: yes
